---

- hosts: all
  become: true
  tasks:

  - name: update repo
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  - name: install php supp for apache
    apt:
      name: libapache2-mod-php
      state: latest
